CREATE DATABASE CUSTOMER;
USE CUSTOMER;
CREATE TABLE IF NOT EXISTS PAYMENT1 (
CUST_ID INT (4) PRIMARY KEY,
NAME VARCHAR(50), 
MODE VARCHAR(20),
CITY VARCHAR(20) NOT NULL
);
INSERT INTO PAYMENT1 (CUST_ID, NAME , MODE, CITY) VALUES
(101,"OLIVIA BARRETT", "NET BANKING", "PORTLAND"),
(102,"ETHAN SINCLAIR", "CREDIT CARD", "MIAMI"),
(103,"MAYA HERMANDEZ","CREDIT CARD", "SEATTLE"),
(104,"LIAM DONOVAN", "NET BANKING", "DENVER"),
(105, "SOPHIA NGUYEN", "CREDIT CARD", "NEW ORKEANS"),
(106, "CALEB FOSTER", "DEBIT CARD", "MINNEAPOLIS"),
(107,"AVA PATEL", "DEBIT CARD", "PHOENIX"),
(108, "LUCAS CARTER", "NET BANKING", "BOSTEN"),
(109, "ISABELLA MARTINEZ", "NET BANKING", "NASHVILLE"),
(110, "JACKSON BROOKS", "CREDIT CARD", "BOSTEN");
 
 SELECT * FROM PAYMENT;
 
 # TOTAL PAYMENT ACCORDING TO EACH PAYMENT MODE?
 SELECT MODE 
 FROM PAYMENT
 GROUP BY MODE;
 # COUNT OF EACH MODE BY ASCENDING ORDER?
 SELECT MODE, COUNT(MODE)
 FROM PAYMENT
 GROUP BY MODE
 ORDER BY MODE ASC;
 # TOTAL PAYMENT ACCORDING TO EACH PAYMENT METHOD?
 SELECT MODE, COUNT(NAME)
 FROM PAYMENT1
 GROUP BY MODE;
 
 CREATE DATABASE SCHOOL;
 USE SCHOOL;
 CREATE TABLE IF NOT EXISTS STUDENT (
 ROLL_NO INT (2) PRIMARY KEY,
 NAME VARCHAR(50),
 MARKS INT(3),
 GRADE VARCHAR (1),
 CITY VARCHAR (50));
 
 INSERT INTO STUDENT (ROLL_NO, NAME, MARKS, GRADE, CITY) VALUES
 (01, "ANIL", 78, "C", "PUNE"),
 (02, "BHUMIKA", 93, "A", "MUMBAI"),
 (03, "CHETAN", 85, "B", "MUMBAI"),
 (04, "DHRUV", 96, "A", "DELHI"),
 (05, "EMANUAL", 12, "F", "DELHI"),
 (06, "FARAH", 82, "B" , "DELHI");
 
 SELECT GRADE ,COUNT(NAME)
 FROM STUDENT 
 GROUP BY GRADE
 ORDER BY GRADE;
 
 SELECT GRADE,NAME , COUNT(NAME)
 FROM STUDENT
 GROUP BY GRADE,NAME
 ORDER BY GRADE;
 
 SELECT DISTINCT CITY FROM STUDENT;
 SELECT * FROM STUDENT
 WHERE MARKS > 90;

SELECT * 
FROM STUDENT
WHERE MARKS BETWEEN 70 AND 90
GROUP BY GRADE
HAVING MARKS > 70
ORDER BY GRADE ASC;

-- HAVING CLAUSE , WE USE THIS WHERE WE CAN NOT USE WHERE FOR ANY CONDITION.
SELECT COUNT(NAME), CITY
FROM STUDENT
GROUP BY CITY
HAVING MAX(MARKS) > 90;

SELECT CITY, COUNT(ROLL_NO)
FROM STUDENT
GROUP BY CITY
HAVING MAX(MARKS) > 90;
